---
- name: "configuration play." 
  hosts: web
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: "Wait 90 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        timeout: 90

  roles:
    # Your code here
    - configure-server