---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Get path
  shell: |
    echo "pwd"
    pwd

- name: Copy backend page
  copy:
    src: "/root/project/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"
    backup: yes

- name: Executing node
  shell: |
    cd ~/web
    tar -xzf artifact.tar.gz
    pm2 stop default
    pm2 start npm -- start