---
- name: "update apt package"
  become: true
  apt:
    update_cache: yes

- name: "update package"
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies no longer require"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create backend
  become: true
  shell: |
    mkdir /home/ubuntu/backend
    cp /home/ubuntu/artifact.tar.gz backend/
    cd backend/
    tar -xvf artifact.tar.gz
- name: Start backend
  become: true
  shell: |
    cd /home/ubuntu/backend/
    npm install
    pm2 stop default
    pm2 start npm -- start